// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNo9O2lyCfLuEUODXdu4ehr7KtUVBY6F8',
    appId: '1:231082636414:web:ed01be4d5a762126d2142f',
    messagingSenderId: '231082636414',
    projectId: 'chat-app-v1-flutter',
    authDomain: 'chat-app-v1-flutter.firebaseapp.com',
    storageBucket: 'chat-app-v1-flutter.firebasestorage.app',
    measurementId: 'G-V5JSNC4DB8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqfxJjq9QV0QqG9926b-qap7cpwiOLZK4',
    appId: '1:231082636414:android:b93632d30c452cb1d2142f',
    messagingSenderId: '231082636414',
    projectId: 'chat-app-v1-flutter',
    storageBucket: 'chat-app-v1-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRIpvoKVRiH5tKbOKtDOG7RTwbgGFZG_k',
    appId: '1:231082636414:ios:15b9d4bf6880db55d2142f',
    messagingSenderId: '231082636414',
    projectId: 'chat-app-v1-flutter',
    storageBucket: 'chat-app-v1-flutter.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );
}
